/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev */

#include "proto/gateway/generic.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(gateway_GatewayStatus, gateway_GatewayStatus, AUTO)



/* @@protoc_insertion_point(eof) */
