/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/device.proto */

#ifndef PROTOBUF_C_proto_2fdevice_2eproto__INCLUDED
#define PROTOBUF_C_proto_2fdevice_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Home__StatusReport Home__StatusReport;


/* --- enums --- */


/* --- messages --- */

struct  _Home__StatusReport
{
  ProtobufCMessage base;
  /*
   * Unique Device ID
   */
  uint64_t device_id;
  /*
   * Status details - device specific
   */
  ProtobufCBinaryData details;
};
#define HOME__STATUS_REPORT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&home__status_report__descriptor) \
    , 0, {0,NULL} }


/* Home__StatusReport methods */
void   home__status_report__init
                     (Home__StatusReport         *message);
size_t home__status_report__get_packed_size
                     (const Home__StatusReport   *message);
size_t home__status_report__pack
                     (const Home__StatusReport   *message,
                      uint8_t             *out);
size_t home__status_report__pack_to_buffer
                     (const Home__StatusReport   *message,
                      ProtobufCBuffer     *buffer);
Home__StatusReport *
       home__status_report__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   home__status_report__free_unpacked
                     (Home__StatusReport *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Home__StatusReport_Closure)
                 (const Home__StatusReport *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor home__status_report__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_proto_2fdevice_2eproto__INCLUDED */
