/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/device.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "proto/device.pb-c.h"
void   home__status_report__init
                     (Home__StatusReport         *message)
{
  static const Home__StatusReport init_value = HOME__STATUS_REPORT__INIT;
  *message = init_value;
}
size_t home__status_report__get_packed_size
                     (const Home__StatusReport *message)
{
  assert(message->base.descriptor == &home__status_report__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t home__status_report__pack
                     (const Home__StatusReport *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &home__status_report__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t home__status_report__pack_to_buffer
                     (const Home__StatusReport *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &home__status_report__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Home__StatusReport *
       home__status_report__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Home__StatusReport *)
     protobuf_c_message_unpack (&home__status_report__descriptor,
                                allocator, len, data);
}
void   home__status_report__free_unpacked
                     (Home__StatusReport *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &home__status_report__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor home__status_report__field_descriptors[2] =
{
  {
    "device_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Home__StatusReport, device_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "details",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Home__StatusReport, details),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned home__status_report__field_indices_by_name[] = {
  1,   /* field[1] = details */
  0,   /* field[0] = device_id */
};
static const ProtobufCIntRange home__status_report__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor home__status_report__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "home.StatusReport",
  "StatusReport",
  "Home__StatusReport",
  "home",
  sizeof(Home__StatusReport),
  2,
  home__status_report__field_descriptors,
  home__status_report__field_indices_by_name,
  1,  home__status_report__number_ranges,
  (ProtobufCMessageInit) home__status_report__init,
  NULL,NULL,NULL    /* reserved[123] */
};
