/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev */

#ifndef PB_HOME_PROTO_JOIN_PB_H_INCLUDED
#define PB_HOME_PROTO_JOIN_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _home_JoinRequest {
    uint64_t device_id;
    pb_callback_t device_name;
    pb_callback_t device_manufacturer;
    pb_callback_t device_url;
    pb_callback_t proto_status_message_url;
    pb_callback_t proto_config_message_url;
/* @@protoc_insertion_point(struct:home_JoinRequest) */
} home_JoinRequest;


/* Initializer values for message structs */
#define home_JoinRequest_init_default            {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define home_JoinRequest_init_zero               {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define home_JoinRequest_device_id_tag           1
#define home_JoinRequest_device_name_tag         2
#define home_JoinRequest_device_manufacturer_tag 3
#define home_JoinRequest_device_url_tag          4
#define home_JoinRequest_proto_status_message_url_tag 10
#define home_JoinRequest_proto_config_message_url_tag 11

/* Struct field encoding specification for nanopb */
#define home_JoinRequest_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, UINT64, device_id, 1) \
X(a, CALLBACK, SINGULAR, STRING, device_name, 2) \
X(a, CALLBACK, SINGULAR, STRING, device_manufacturer, 3) \
X(a, CALLBACK, SINGULAR, STRING, device_url, 4) \
X(a, CALLBACK, SINGULAR, STRING, proto_status_message_url, 10) \
X(a, CALLBACK, SINGULAR, STRING, proto_config_message_url, 11)
#define home_JoinRequest_CALLBACK pb_default_field_callback
#define home_JoinRequest_DEFAULT NULL

extern const pb_msgdesc_t home_JoinRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define home_JoinRequest_fields &home_JoinRequest_msg

/* Maximum encoded size of messages (where known) */
/* home_JoinRequest_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
