/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/join.proto */

#ifndef PROTOBUF_C_proto_2fjoin_2eproto__INCLUDED
#define PROTOBUF_C_proto_2fjoin_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Home__JoinRequest Home__JoinRequest;


/* --- enums --- */


/* --- messages --- */

struct  _Home__JoinRequest
{
  ProtobufCMessage base;
  /*
   * Unique Device ID
   */
  uint64_t device_id;
  /*
   * Device details
   */
  char *device_name;
  char *device_manufacturer;
  char *device_url;
  /*
   * protobuf urls
   */
  char *proto_status_message_url;
  char *proto_config_message_url;
};
#define HOME__JOIN_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&home__join_request__descriptor) \
    , 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/* Home__JoinRequest methods */
void   home__join_request__init
                     (Home__JoinRequest         *message);
size_t home__join_request__get_packed_size
                     (const Home__JoinRequest   *message);
size_t home__join_request__pack
                     (const Home__JoinRequest   *message,
                      uint8_t             *out);
size_t home__join_request__pack_to_buffer
                     (const Home__JoinRequest   *message,
                      ProtobufCBuffer     *buffer);
Home__JoinRequest *
       home__join_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   home__join_request__free_unpacked
                     (Home__JoinRequest *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Home__JoinRequest_Closure)
                 (const Home__JoinRequest *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor home__join_request__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_proto_2fjoin_2eproto__INCLUDED */
