/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/join.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "proto/join.pb-c.h"
void   home__join_request__init
                     (Home__JoinRequest         *message)
{
  static const Home__JoinRequest init_value = HOME__JOIN_REQUEST__INIT;
  *message = init_value;
}
size_t home__join_request__get_packed_size
                     (const Home__JoinRequest *message)
{
  assert(message->base.descriptor == &home__join_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t home__join_request__pack
                     (const Home__JoinRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &home__join_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t home__join_request__pack_to_buffer
                     (const Home__JoinRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &home__join_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Home__JoinRequest *
       home__join_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Home__JoinRequest *)
     protobuf_c_message_unpack (&home__join_request__descriptor,
                                allocator, len, data);
}
void   home__join_request__free_unpacked
                     (Home__JoinRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &home__join_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor home__join_request__field_descriptors[6] =
{
  {
    "device_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Home__JoinRequest, device_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Home__JoinRequest, device_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_manufacturer",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Home__JoinRequest, device_manufacturer),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_url",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Home__JoinRequest, device_url),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proto_status_message_url",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Home__JoinRequest, proto_status_message_url),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proto_config_message_url",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Home__JoinRequest, proto_config_message_url),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned home__join_request__field_indices_by_name[] = {
  0,   /* field[0] = device_id */
  2,   /* field[2] = device_manufacturer */
  1,   /* field[1] = device_name */
  3,   /* field[3] = device_url */
  5,   /* field[5] = proto_config_message_url */
  4,   /* field[4] = proto_status_message_url */
};
static const ProtobufCIntRange home__join_request__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 10, 4 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor home__join_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "home.JoinRequest",
  "JoinRequest",
  "Home__JoinRequest",
  "home",
  sizeof(Home__JoinRequest),
  6,
  home__join_request__field_descriptors,
  home__join_request__field_indices_by_name,
  2,  home__join_request__number_ranges,
  (ProtobufCMessageInit) home__join_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
