// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/light/led_strip.proto

package light

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LedStripStatus struct {
	// An auto incremented value
	Sequence uint32 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Magic number. Always 0x33445566
	Magic uint32 `protobuf:"varint,2,opt,name=magic,proto3" json:"magic,omitempty"`
	// LED strip channels, just value
	Channels             []uint32 `protobuf:"varint,3,rep,packed,name=channels,proto3" json:"channels,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LedStripStatus) Reset()         { *m = LedStripStatus{} }
func (m *LedStripStatus) String() string { return proto.CompactTextString(m) }
func (*LedStripStatus) ProtoMessage()    {}
func (*LedStripStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_8091835df418c1f4, []int{0}
}

func (m *LedStripStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LedStripStatus.Unmarshal(m, b)
}
func (m *LedStripStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LedStripStatus.Marshal(b, m, deterministic)
}
func (m *LedStripStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LedStripStatus.Merge(m, src)
}
func (m *LedStripStatus) XXX_Size() int {
	return xxx_messageInfo_LedStripStatus.Size(m)
}
func (m *LedStripStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_LedStripStatus.DiscardUnknown(m)
}

var xxx_messageInfo_LedStripStatus proto.InternalMessageInfo

func (m *LedStripStatus) GetSequence() uint32 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *LedStripStatus) GetMagic() uint32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *LedStripStatus) GetChannels() []uint32 {
	if m != nil {
		return m.Channels
	}
	return nil
}

func init() {
	proto.RegisterType((*LedStripStatus)(nil), "light.LedStripStatus")
}

func init() { proto.RegisterFile("proto/light/led_strip.proto", fileDescriptor_8091835df418c1f4) }

var fileDescriptor_8091835df418c1f4 = []byte{
	// 128 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0xc9, 0x4c, 0xcf, 0x28, 0xd1, 0xcf, 0x49, 0x4d, 0x89, 0x2f, 0x2e, 0x29, 0xca,
	0x2c, 0xd0, 0x03, 0x8b, 0x0a, 0xb1, 0x82, 0x85, 0x95, 0xe2, 0xb8, 0xf8, 0x7c, 0x52, 0x53, 0x82,
	0x41, 0x12, 0xc1, 0x25, 0x89, 0x25, 0xa5, 0xc5, 0x42, 0x52, 0x5c, 0x1c, 0xc5, 0xa9, 0x85, 0xa5,
	0xa9, 0x79, 0xc9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xbc, 0x41, 0x70, 0xbe, 0x90, 0x08, 0x17,
	0x6b, 0x6e, 0x62, 0x7a, 0x66, 0xb2, 0x04, 0x13, 0x58, 0x02, 0xc2, 0x01, 0xe9, 0x48, 0xce, 0x48,
	0xcc, 0xcb, 0x4b, 0xcd, 0x29, 0x96, 0x60, 0x56, 0x60, 0x06, 0xe9, 0x80, 0xf1, 0x93, 0xd8, 0xc0,
	0xb6, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x84, 0xbd, 0x93, 0x8c, 0x00, 0x00, 0x00,
}
