/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/sensor/base.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "proto/sensor/base.pb-c.h"
void   sensors__temperature__init
                     (Sensors__Temperature         *message)
{
  static const Sensors__Temperature init_value = SENSORS__TEMPERATURE__INIT;
  *message = init_value;
}
size_t sensors__temperature__get_packed_size
                     (const Sensors__Temperature *message)
{
  assert(message->base.descriptor == &sensors__temperature__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sensors__temperature__pack
                     (const Sensors__Temperature *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sensors__temperature__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sensors__temperature__pack_to_buffer
                     (const Sensors__Temperature *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sensors__temperature__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Sensors__Temperature *
       sensors__temperature__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Sensors__Temperature *)
     protobuf_c_message_unpack (&sensors__temperature__descriptor,
                                allocator, len, data);
}
void   sensors__temperature__free_unpacked
                     (Sensors__Temperature *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sensors__temperature__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sensors__humidity__init
                     (Sensors__Humidity         *message)
{
  static const Sensors__Humidity init_value = SENSORS__HUMIDITY__INIT;
  *message = init_value;
}
size_t sensors__humidity__get_packed_size
                     (const Sensors__Humidity *message)
{
  assert(message->base.descriptor == &sensors__humidity__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sensors__humidity__pack
                     (const Sensors__Humidity *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sensors__humidity__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sensors__humidity__pack_to_buffer
                     (const Sensors__Humidity *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sensors__humidity__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Sensors__Humidity *
       sensors__humidity__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Sensors__Humidity *)
     protobuf_c_message_unpack (&sensors__humidity__descriptor,
                                allocator, len, data);
}
void   sensors__humidity__free_unpacked
                     (Sensors__Humidity *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sensors__humidity__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sensors__ambient_light__init
                     (Sensors__AmbientLight         *message)
{
  static const Sensors__AmbientLight init_value = SENSORS__AMBIENT_LIGHT__INIT;
  *message = init_value;
}
size_t sensors__ambient_light__get_packed_size
                     (const Sensors__AmbientLight *message)
{
  assert(message->base.descriptor == &sensors__ambient_light__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sensors__ambient_light__pack
                     (const Sensors__AmbientLight *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sensors__ambient_light__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sensors__ambient_light__pack_to_buffer
                     (const Sensors__AmbientLight *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sensors__ambient_light__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Sensors__AmbientLight *
       sensors__ambient_light__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Sensors__AmbientLight *)
     protobuf_c_message_unpack (&sensors__ambient_light__descriptor,
                                allocator, len, data);
}
void   sensors__ambient_light__free_unpacked
                     (Sensors__AmbientLight *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sensors__ambient_light__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sensors__battery__init
                     (Sensors__Battery         *message)
{
  static const Sensors__Battery init_value = SENSORS__BATTERY__INIT;
  *message = init_value;
}
size_t sensors__battery__get_packed_size
                     (const Sensors__Battery *message)
{
  assert(message->base.descriptor == &sensors__battery__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sensors__battery__pack
                     (const Sensors__Battery *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sensors__battery__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sensors__battery__pack_to_buffer
                     (const Sensors__Battery *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sensors__battery__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Sensors__Battery *
       sensors__battery__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Sensors__Battery *)
     protobuf_c_message_unpack (&sensors__battery__descriptor,
                                allocator, len, data);
}
void   sensors__battery__free_unpacked
                     (Sensors__Battery *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sensors__battery__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor sensors__temperature__field_descriptors[2] =
{
  {
    "value_c",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Sensors__Temperature, value_c),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value_f",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Sensors__Temperature, value_f),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sensors__temperature__field_indices_by_name[] = {
  0,   /* field[0] = value_c */
  1,   /* field[1] = value_f */
};
static const ProtobufCIntRange sensors__temperature__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sensors__temperature__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sensors.Temperature",
  "Temperature",
  "Sensors__Temperature",
  "sensors",
  sizeof(Sensors__Temperature),
  2,
  sensors__temperature__field_descriptors,
  sensors__temperature__field_indices_by_name,
  1,  sensors__temperature__number_ranges,
  (ProtobufCMessageInit) sensors__temperature__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sensors__humidity__field_descriptors[1] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Sensors__Humidity, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sensors__humidity__field_indices_by_name[] = {
  0,   /* field[0] = value */
};
static const ProtobufCIntRange sensors__humidity__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor sensors__humidity__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sensors.Humidity",
  "Humidity",
  "Sensors__Humidity",
  "sensors",
  sizeof(Sensors__Humidity),
  1,
  sensors__humidity__field_descriptors,
  sensors__humidity__field_indices_by_name,
  1,  sensors__humidity__number_ranges,
  (ProtobufCMessageInit) sensors__humidity__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sensors__ambient_light__field_descriptors[1] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Sensors__AmbientLight, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sensors__ambient_light__field_indices_by_name[] = {
  0,   /* field[0] = value */
};
static const ProtobufCIntRange sensors__ambient_light__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor sensors__ambient_light__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sensors.AmbientLight",
  "AmbientLight",
  "Sensors__AmbientLight",
  "sensors",
  sizeof(Sensors__AmbientLight),
  1,
  sensors__ambient_light__field_descriptors,
  sensors__ambient_light__field_indices_by_name,
  1,  sensors__ambient_light__number_ranges,
  (ProtobufCMessageInit) sensors__ambient_light__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sensors__battery__field_descriptors[2] =
{
  {
    "percent",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Sensors__Battery, percent),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "voltage_mv",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Sensors__Battery, voltage_mv),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sensors__battery__field_indices_by_name[] = {
  0,   /* field[0] = percent */
  1,   /* field[1] = voltage_mv */
};
static const ProtobufCIntRange sensors__battery__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sensors__battery__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sensors.Battery",
  "Battery",
  "Sensors__Battery",
  "sensors",
  sizeof(Sensors__Battery),
  2,
  sensors__battery__field_descriptors,
  sensors__battery__field_indices_by_name,
  1,  sensors__battery__number_ranges,
  (ProtobufCMessageInit) sensors__battery__init,
  NULL,NULL,NULL    /* reserved[123] */
};
