/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/sensor/multisensor.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "proto/sensor/multisensor.pb-c.h"
void   sensors__multi_sensor_status__init
                     (Sensors__MultiSensorStatus         *message)
{
  static const Sensors__MultiSensorStatus init_value = SENSORS__MULTI_SENSOR_STATUS__INIT;
  *message = init_value;
}
size_t sensors__multi_sensor_status__get_packed_size
                     (const Sensors__MultiSensorStatus *message)
{
  assert(message->base.descriptor == &sensors__multi_sensor_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sensors__multi_sensor_status__pack
                     (const Sensors__MultiSensorStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sensors__multi_sensor_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sensors__multi_sensor_status__pack_to_buffer
                     (const Sensors__MultiSensorStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sensors__multi_sensor_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Sensors__MultiSensorStatus *
       sensors__multi_sensor_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Sensors__MultiSensorStatus *)
     protobuf_c_message_unpack (&sensors__multi_sensor_status__descriptor,
                                allocator, len, data);
}
void   sensors__multi_sensor_status__free_unpacked
                     (Sensors__MultiSensorStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sensors__multi_sensor_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor sensors__multi_sensor_status__field_descriptors[6] =
{
  {
    "sequence",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Sensors__MultiSensorStatus, sequence),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "crc",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Sensors__MultiSensorStatus, crc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "temperature",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Sensors__MultiSensorStatus, temperature),
    &sensors__temperature__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "humidity",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Sensors__MultiSensorStatus, humidity),
    &sensors__humidity__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ambient_light",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Sensors__MultiSensorStatus, ambient_light),
    &sensors__ambient_light__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "battery",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Sensors__MultiSensorStatus, battery),
    &sensors__battery__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sensors__multi_sensor_status__field_indices_by_name[] = {
  4,   /* field[4] = ambient_light */
  5,   /* field[5] = battery */
  1,   /* field[1] = crc */
  3,   /* field[3] = humidity */
  0,   /* field[0] = sequence */
  2,   /* field[2] = temperature */
};
static const ProtobufCIntRange sensors__multi_sensor_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor sensors__multi_sensor_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sensors.MultiSensorStatus",
  "MultiSensorStatus",
  "Sensors__MultiSensorStatus",
  "sensors",
  sizeof(Sensors__MultiSensorStatus),
  6,
  sensors__multi_sensor_status__field_descriptors,
  sensors__multi_sensor_status__field_indices_by_name,
  1,  sensors__multi_sensor_status__number_ranges,
  (ProtobufCMessageInit) sensors__multi_sensor_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
