/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/sensor/multisensor.proto */

#ifndef PROTOBUF_C_proto_2fsensor_2fmultisensor_2eproto__INCLUDED
#define PROTOBUF_C_proto_2fsensor_2fmultisensor_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "proto/sensor/base.pb-c.h"

typedef struct _Sensors__MultiSensorStatus Sensors__MultiSensorStatus;


/* --- enums --- */


/* --- messages --- */

struct  _Sensors__MultiSensorStatus
{
  ProtobufCMessage base;
  /*
   * An auto incremented value
   */
  uint32_t sequence;
  /*
   * Control sum
   */
  uint32_t crc;
  /*
   * Sensors
   */
  Sensors__Temperature *temperature;
  Sensors__Humidity *humidity;
  Sensors__AmbientLight *ambient_light;
  Sensors__Battery *battery;
};
#define SENSORS__MULTI_SENSOR_STATUS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sensors__multi_sensor_status__descriptor) \
    , 0, 0, NULL, NULL, NULL, NULL }


/* Sensors__MultiSensorStatus methods */
void   sensors__multi_sensor_status__init
                     (Sensors__MultiSensorStatus         *message);
size_t sensors__multi_sensor_status__get_packed_size
                     (const Sensors__MultiSensorStatus   *message);
size_t sensors__multi_sensor_status__pack
                     (const Sensors__MultiSensorStatus   *message,
                      uint8_t             *out);
size_t sensors__multi_sensor_status__pack_to_buffer
                     (const Sensors__MultiSensorStatus   *message,
                      ProtobufCBuffer     *buffer);
Sensors__MultiSensorStatus *
       sensors__multi_sensor_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sensors__multi_sensor_status__free_unpacked
                     (Sensors__MultiSensorStatus *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Sensors__MultiSensorStatus_Closure)
                 (const Sensors__MultiSensorStatus *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor sensors__multi_sensor_status__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_proto_2fsensor_2fmultisensor_2eproto__INCLUDED */
