// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateway/generic.proto

package gateway

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GatewayStatus struct {
	// An auto increment value
	Sequence uint64 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// For devices with backup battery:
	// true if running on battery
	BatteryMode bool `protobuf:"varint,2,opt,name=battery_mode,json=batteryMode,proto3" json:"battery_mode,omitempty"`
	// Packet counters
	LoraReceived    uint64 `protobuf:"varint,20,opt,name=lora_received,json=loraReceived,proto3" json:"lora_received,omitempty"`
	LoraSend        uint64 `protobuf:"varint,21,opt,name=lora_send,json=loraSend,proto3" json:"lora_send,omitempty"`
	NetworkReceived uint64 `protobuf:"varint,22,opt,name=network_received,json=networkReceived,proto3" json:"network_received,omitempty"`
	NetworkSend     uint64 `protobuf:"varint,23,opt,name=network_send,json=networkSend,proto3" json:"network_send,omitempty"`
	// Error counters
	LoraCrcError         uint64   `protobuf:"varint,40,opt,name=lora_crc_error,json=loraCrcError,proto3" json:"lora_crc_error,omitempty"`
	SpiTimeout           uint64   `protobuf:"varint,41,opt,name=spi_timeout,json=spiTimeout,proto3" json:"spi_timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GatewayStatus) Reset()         { *m = GatewayStatus{} }
func (m *GatewayStatus) String() string { return proto.CompactTextString(m) }
func (*GatewayStatus) ProtoMessage()    {}
func (*GatewayStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_4900a36d21fe355c, []int{0}
}

func (m *GatewayStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GatewayStatus.Unmarshal(m, b)
}
func (m *GatewayStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GatewayStatus.Marshal(b, m, deterministic)
}
func (m *GatewayStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GatewayStatus.Merge(m, src)
}
func (m *GatewayStatus) XXX_Size() int {
	return xxx_messageInfo_GatewayStatus.Size(m)
}
func (m *GatewayStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_GatewayStatus.DiscardUnknown(m)
}

var xxx_messageInfo_GatewayStatus proto.InternalMessageInfo

func (m *GatewayStatus) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *GatewayStatus) GetBatteryMode() bool {
	if m != nil {
		return m.BatteryMode
	}
	return false
}

func (m *GatewayStatus) GetLoraReceived() uint64 {
	if m != nil {
		return m.LoraReceived
	}
	return 0
}

func (m *GatewayStatus) GetLoraSend() uint64 {
	if m != nil {
		return m.LoraSend
	}
	return 0
}

func (m *GatewayStatus) GetNetworkReceived() uint64 {
	if m != nil {
		return m.NetworkReceived
	}
	return 0
}

func (m *GatewayStatus) GetNetworkSend() uint64 {
	if m != nil {
		return m.NetworkSend
	}
	return 0
}

func (m *GatewayStatus) GetLoraCrcError() uint64 {
	if m != nil {
		return m.LoraCrcError
	}
	return 0
}

func (m *GatewayStatus) GetSpiTimeout() uint64 {
	if m != nil {
		return m.SpiTimeout
	}
	return 0
}

func init() {
	proto.RegisterType((*GatewayStatus)(nil), "gateway.GatewayStatus")
}

func init() { proto.RegisterFile("gateway/generic.proto", fileDescriptor_4900a36d21fe355c) }

var fileDescriptor_4900a36d21fe355c = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x95, 0x0a, 0x41, 0xb9, 0xa4, 0x80, 0x2c, 0x0a, 0x16, 0x0c, 0xb4, 0xc0, 0x90, 0x2e,
	0x30, 0xf0, 0x08, 0x08, 0x31, 0xb1, 0xa4, 0xec, 0x91, 0x6b, 0x9f, 0x2a, 0x0b, 0x6a, 0x87, 0xb3,
	0x43, 0xd5, 0x07, 0xe2, 0x3d, 0x51, 0x2e, 0x6e, 0xb3, 0xd9, 0x9f, 0x3e, 0x7d, 0xbf, 0x65, 0x98,
	0xae, 0x55, 0xc4, 0xad, 0xda, 0x3d, 0xaf, 0xd1, 0x21, 0x59, 0xfd, 0xd4, 0x90, 0x8f, 0x5e, 0x9c,
	0x24, 0x7c, 0xff, 0x37, 0x82, 0xc9, 0x7b, 0x7f, 0x5e, 0x46, 0x15, 0xdb, 0x20, 0x6e, 0x60, 0x1c,
	0xf0, 0xa7, 0x45, 0xa7, 0x51, 0x66, 0xb3, 0xac, 0x3c, 0xaa, 0x0e, 0x77, 0x31, 0x87, 0x62, 0xa5,
	0x62, 0x44, 0xda, 0xd5, 0x1b, 0x6f, 0x50, 0x8e, 0x66, 0x59, 0x39, 0xae, 0xf2, 0xc4, 0x3e, 0xbc,
	0x41, 0xf1, 0x00, 0x93, 0x6f, 0x4f, 0xaa, 0x26, 0xd4, 0x68, 0x7f, 0xd1, 0xc8, 0x4b, 0x6e, 0x14,
	0x1d, 0xac, 0x12, 0x13, 0xb7, 0x70, 0xca, 0x52, 0x40, 0x67, 0xe4, 0xb4, 0x1f, 0xe9, 0xc0, 0x12,
	0x9d, 0x11, 0x0b, 0xb8, 0x70, 0x18, 0xb7, 0x9e, 0xbe, 0x86, 0xc8, 0x15, 0x3b, 0xe7, 0x89, 0x1f,
	0x3a, 0x73, 0x28, 0xf6, 0x2a, 0xa7, 0xae, 0x59, 0xcb, 0x13, 0xe3, 0xda, 0x23, 0x9c, 0xf1, 0x94,
	0x26, 0x5d, 0x23, 0x91, 0x27, 0x59, 0x0e, 0x0f, 0x7a, 0x25, 0xfd, 0xd6, 0x31, 0x71, 0x07, 0x79,
	0x68, 0x6c, 0x1d, 0xed, 0x06, 0x7d, 0x1b, 0xe5, 0x82, 0x15, 0x08, 0x8d, 0xfd, 0xec, 0xc9, 0xea,
	0x98, 0xff, 0xed, 0xe5, 0x3f, 0x00, 0x00, 0xff, 0xff, 0xef, 0x1a, 0xd4, 0xb4, 0x50, 0x01, 0x00,
	0x00,
}
