/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev */

#ifndef PB_LOVEHEART_PROTO_LOVEHEART_LOVEHEART_PB_H_INCLUDED
#define PB_LOVEHEART_PROTO_LOVEHEART_LOVEHEART_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _loveheart_LoveHeartStatus {
    uint32_t sequence;
    uint32_t magic;
    uint32_t temperature;
    uint32_t humidity;
    uint32_t light_als;
    uint32_t light_white;
    float voltage;
    bool animation;
    uint32_t erros_i2c;
    uint32_t errors_spi;
    uint32_t errors_radio;
/* @@protoc_insertion_point(struct:loveheart_LoveHeartStatus) */
} loveheart_LoveHeartStatus;


typedef struct _loveheart_LoveHeartStatusResponse {
    uint32_t sequence;
    uint32_t magic;
    bool enable_animation;
/* @@protoc_insertion_point(struct:loveheart_LoveHeartStatusResponse) */
} loveheart_LoveHeartStatusResponse;


/* Initializer values for message structs */
#define loveheart_LoveHeartStatus_init_default   {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define loveheart_LoveHeartStatusResponse_init_default {0, 0, 0}
#define loveheart_LoveHeartStatus_init_zero      {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define loveheart_LoveHeartStatusResponse_init_zero {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define loveheart_LoveHeartStatus_sequence_tag   1
#define loveheart_LoveHeartStatus_magic_tag      2
#define loveheart_LoveHeartStatus_temperature_tag 3
#define loveheart_LoveHeartStatus_humidity_tag   4
#define loveheart_LoveHeartStatus_light_als_tag  5
#define loveheart_LoveHeartStatus_light_white_tag 6
#define loveheart_LoveHeartStatus_voltage_tag    7
#define loveheart_LoveHeartStatus_animation_tag  8
#define loveheart_LoveHeartStatus_erros_i2c_tag  20
#define loveheart_LoveHeartStatus_errors_spi_tag 21
#define loveheart_LoveHeartStatus_errors_radio_tag 22
#define loveheart_LoveHeartStatusResponse_sequence_tag 1
#define loveheart_LoveHeartStatusResponse_magic_tag 2
#define loveheart_LoveHeartStatusResponse_enable_animation_tag 3

/* Struct field encoding specification for nanopb */
#define loveheart_LoveHeartStatus_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, UINT32, sequence, 1) \
X(a, STATIC, SINGULAR, UINT32, magic, 2) \
X(a, STATIC, SINGULAR, UINT32, temperature, 3) \
X(a, STATIC, SINGULAR, UINT32, humidity, 4) \
X(a, STATIC, SINGULAR, UINT32, light_als, 5) \
X(a, STATIC, SINGULAR, UINT32, light_white, 6) \
X(a, STATIC, SINGULAR, FLOAT, voltage, 7) \
X(a, STATIC, SINGULAR, BOOL, animation, 8) \
X(a, STATIC, SINGULAR, UINT32, erros_i2c, 20) \
X(a, STATIC, SINGULAR, UINT32, errors_spi, 21) \
X(a, STATIC, SINGULAR, UINT32, errors_radio, 22)
#define loveheart_LoveHeartStatus_CALLBACK NULL
#define loveheart_LoveHeartStatus_DEFAULT NULL

#define loveheart_LoveHeartStatusResponse_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, UINT32, sequence, 1) \
X(a, STATIC, SINGULAR, UINT32, magic, 2) \
X(a, STATIC, SINGULAR, BOOL, enable_animation, 3)
#define loveheart_LoveHeartStatusResponse_CALLBACK NULL
#define loveheart_LoveHeartStatusResponse_DEFAULT NULL

extern const pb_msgdesc_t loveheart_LoveHeartStatus_msg;
extern const pb_msgdesc_t loveheart_LoveHeartStatusResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define loveheart_LoveHeartStatus_fields &loveheart_LoveHeartStatus_msg
#define loveheart_LoveHeartStatusResponse_fields &loveheart_LoveHeartStatusResponse_msg

/* Maximum encoded size of messages (where known) */
#define loveheart_LoveHeartStatus_size           64
#define loveheart_LoveHeartStatusResponse_size   14

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
