/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev */

#ifndef PB_SENSOR_PROTO_SENSOR_BASE_PB_H_INCLUDED
#define PB_SENSOR_PROTO_SENSOR_BASE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _sensor_AmbientLight {
    uint32_t value;
/* @@protoc_insertion_point(struct:sensor_AmbientLight) */
} sensor_AmbientLight;


typedef struct _sensor_Battery {
    uint32_t percent;
    uint32_t voltage_mv;
/* @@protoc_insertion_point(struct:sensor_Battery) */
} sensor_Battery;


typedef struct _sensor_Humidity {
    float value;
/* @@protoc_insertion_point(struct:sensor_Humidity) */
} sensor_Humidity;


typedef struct _sensor_Temperature {
    float value_c;
    float value_f;
/* @@protoc_insertion_point(struct:sensor_Temperature) */
} sensor_Temperature;


/* Initializer values for message structs */
#define sensor_Temperature_init_default          {0, 0}
#define sensor_Humidity_init_default             {0}
#define sensor_AmbientLight_init_default         {0}
#define sensor_Battery_init_default              {0, 0}
#define sensor_Temperature_init_zero             {0, 0}
#define sensor_Humidity_init_zero                {0}
#define sensor_AmbientLight_init_zero            {0}
#define sensor_Battery_init_zero                 {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define sensor_AmbientLight_value_tag            1
#define sensor_Battery_percent_tag               1
#define sensor_Battery_voltage_mv_tag            2
#define sensor_Humidity_value_tag                1
#define sensor_Temperature_value_c_tag           1
#define sensor_Temperature_value_f_tag           2

/* Struct field encoding specification for nanopb */
#define sensor_Temperature_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, FLOAT, value_c, 1) \
X(a, STATIC, SINGULAR, FLOAT, value_f, 2)
#define sensor_Temperature_CALLBACK NULL
#define sensor_Temperature_DEFAULT NULL

#define sensor_Humidity_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, FLOAT, value, 1)
#define sensor_Humidity_CALLBACK NULL
#define sensor_Humidity_DEFAULT NULL

#define sensor_AmbientLight_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, UINT32, value, 1)
#define sensor_AmbientLight_CALLBACK NULL
#define sensor_AmbientLight_DEFAULT NULL

#define sensor_Battery_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, UINT32, percent, 1) \
X(a, STATIC, SINGULAR, UINT32, voltage_mv, 2)
#define sensor_Battery_CALLBACK NULL
#define sensor_Battery_DEFAULT NULL

extern const pb_msgdesc_t sensor_Temperature_msg;
extern const pb_msgdesc_t sensor_Humidity_msg;
extern const pb_msgdesc_t sensor_AmbientLight_msg;
extern const pb_msgdesc_t sensor_Battery_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define sensor_Temperature_fields &sensor_Temperature_msg
#define sensor_Humidity_fields &sensor_Humidity_msg
#define sensor_AmbientLight_fields &sensor_AmbientLight_msg
#define sensor_Battery_fields &sensor_Battery_msg

/* Maximum encoded size of messages (where known) */
#define sensor_Temperature_size                  10
#define sensor_Humidity_size                     5
#define sensor_AmbientLight_size                 6
#define sensor_Battery_size                      12

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
