/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev */

#ifndef PB_SENSORS_SENSOR_BASE_PB_H_INCLUDED
#define PB_SENSORS_SENSOR_BASE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _sensors_AmbientLight {
    uint32_t value;
/* @@protoc_insertion_point(struct:sensors_AmbientLight) */
} sensors_AmbientLight;


typedef struct _sensors_Battery {
    uint32_t percent;
    uint32_t voltage_mv;
/* @@protoc_insertion_point(struct:sensors_Battery) */
} sensors_Battery;


typedef struct _sensors_Humidity {
    float value;
/* @@protoc_insertion_point(struct:sensors_Humidity) */
} sensors_Humidity;


typedef struct _sensors_Temperature {
    float value_c;
    float value_f;
/* @@protoc_insertion_point(struct:sensors_Temperature) */
} sensors_Temperature;


/* Initializer values for message structs */
#define sensors_Temperature_init_default         {0, 0}
#define sensors_Humidity_init_default            {0}
#define sensors_AmbientLight_init_default        {0}
#define sensors_Battery_init_default             {0, 0}
#define sensors_Temperature_init_zero            {0, 0}
#define sensors_Humidity_init_zero               {0}
#define sensors_AmbientLight_init_zero           {0}
#define sensors_Battery_init_zero                {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define sensors_AmbientLight_value_tag           1
#define sensors_Battery_percent_tag              1
#define sensors_Battery_voltage_mv_tag           2
#define sensors_Humidity_value_tag               1
#define sensors_Temperature_value_c_tag          1
#define sensors_Temperature_value_f_tag          2

/* Struct field encoding specification for nanopb */
#define sensors_Temperature_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, FLOAT, value_c, 1) \
X(a, STATIC, SINGULAR, FLOAT, value_f, 2)
#define sensors_Temperature_CALLBACK NULL
#define sensors_Temperature_DEFAULT NULL

#define sensors_Humidity_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, FLOAT, value, 1)
#define sensors_Humidity_CALLBACK NULL
#define sensors_Humidity_DEFAULT NULL

#define sensors_AmbientLight_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, UINT32, value, 1)
#define sensors_AmbientLight_CALLBACK NULL
#define sensors_AmbientLight_DEFAULT NULL

#define sensors_Battery_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, UINT32, percent, 1) \
X(a, STATIC, SINGULAR, UINT32, voltage_mv, 2)
#define sensors_Battery_CALLBACK NULL
#define sensors_Battery_DEFAULT NULL

extern const pb_msgdesc_t sensors_Temperature_msg;
extern const pb_msgdesc_t sensors_Humidity_msg;
extern const pb_msgdesc_t sensors_AmbientLight_msg;
extern const pb_msgdesc_t sensors_Battery_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define sensors_Temperature_fields &sensors_Temperature_msg
#define sensors_Humidity_fields &sensors_Humidity_msg
#define sensors_AmbientLight_fields &sensors_AmbientLight_msg
#define sensors_Battery_fields &sensors_Battery_msg

/* Maximum encoded size of messages (where known) */
#define sensors_Temperature_size                 10
#define sensors_Humidity_size                    5
#define sensors_AmbientLight_size                6
#define sensors_Battery_size                     12

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
