/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev */

#include "sensor/base.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(sensors_Temperature, sensors_Temperature, AUTO)


PB_BIND(sensors_Humidity, sensors_Humidity, AUTO)


PB_BIND(sensors_AmbientLight, sensors_AmbientLight, AUTO)


PB_BIND(sensors_Battery, sensors_Battery, AUTO)



/* @@protoc_insertion_point(eof) */
