/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev */

#include "sensor/base.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(sensor_Temperature, sensor_Temperature, AUTO)


PB_BIND(sensor_Humidity, sensor_Humidity, AUTO)


PB_BIND(sensor_AmbientLight, sensor_AmbientLight, AUTO)


PB_BIND(sensor_Battery, sensor_Battery, AUTO)



/* @@protoc_insertion_point(eof) */
