/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev */

#ifndef PB_SENSORS_SENSOR_MULTISENSOR_PB_H_INCLUDED
#define PB_SENSORS_SENSOR_MULTISENSOR_PB_H_INCLUDED
#include <pb.h>

#include "sensor/base.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _sensors_MultiSensorStatus {
    uint32_t sequence;
    uint32_t crc;
    sensors_Temperature temperature;
    sensors_Humidity humidity;
    sensors_AmbientLight ambient_light;
    sensors_Battery battery;
/* @@protoc_insertion_point(struct:sensors_MultiSensorStatus) */
} sensors_MultiSensorStatus;


/* Initializer values for message structs */
#define sensors_MultiSensorStatus_init_default   {0, 0, sensors_Temperature_init_default, sensors_Humidity_init_default, sensors_AmbientLight_init_default, sensors_Battery_init_default}
#define sensors_MultiSensorStatus_init_zero      {0, 0, sensors_Temperature_init_zero, sensors_Humidity_init_zero, sensors_AmbientLight_init_zero, sensors_Battery_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define sensors_MultiSensorStatus_sequence_tag   1
#define sensors_MultiSensorStatus_crc_tag        2
#define sensors_MultiSensorStatus_temperature_tag 3
#define sensors_MultiSensorStatus_humidity_tag   4
#define sensors_MultiSensorStatus_ambient_light_tag 5
#define sensors_MultiSensorStatus_battery_tag    6

/* Struct field encoding specification for nanopb */
#define sensors_MultiSensorStatus_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, UINT32, sequence, 1) \
X(a, STATIC, SINGULAR, UINT32, crc, 2) \
X(a, STATIC, SINGULAR, MESSAGE, temperature, 3) \
X(a, STATIC, SINGULAR, MESSAGE, humidity, 4) \
X(a, STATIC, SINGULAR, MESSAGE, ambient_light, 5) \
X(a, STATIC, SINGULAR, MESSAGE, battery, 6)
#define sensors_MultiSensorStatus_CALLBACK NULL
#define sensors_MultiSensorStatus_DEFAULT NULL
#define sensors_MultiSensorStatus_temperature_MSGTYPE sensors_Temperature
#define sensors_MultiSensorStatus_humidity_MSGTYPE sensors_Humidity
#define sensors_MultiSensorStatus_ambient_light_MSGTYPE sensors_AmbientLight
#define sensors_MultiSensorStatus_battery_MSGTYPE sensors_Battery

extern const pb_msgdesc_t sensors_MultiSensorStatus_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define sensors_MultiSensorStatus_fields &sensors_MultiSensorStatus_msg

/* Maximum encoded size of messages (where known) */
#define sensors_MultiSensorStatus_size           53

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
