// Code generated by protoc-gen-go. DO NOT EDIT.
// source: device.proto

package openiot

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatusReport struct {
	DeviceId             uint64   `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	MessageSize          uint32   `protobuf:"varint,2,opt,name=message_size,json=messageSize,proto3" json:"message_size,omitempty"`
	Details              []byte   `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusReport) Reset()         { *m = StatusReport{} }
func (m *StatusReport) String() string { return proto.CompactTextString(m) }
func (*StatusReport) ProtoMessage()    {}
func (*StatusReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_870276a56ac00da5, []int{0}
}

func (m *StatusReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusReport.Unmarshal(m, b)
}
func (m *StatusReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusReport.Marshal(b, m, deterministic)
}
func (m *StatusReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusReport.Merge(m, src)
}
func (m *StatusReport) XXX_Size() int {
	return xxx_messageInfo_StatusReport.Size(m)
}
func (m *StatusReport) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusReport.DiscardUnknown(m)
}

var xxx_messageInfo_StatusReport proto.InternalMessageInfo

func (m *StatusReport) GetDeviceId() uint64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *StatusReport) GetMessageSize() uint32 {
	if m != nil {
		return m.MessageSize
	}
	return 0
}

func (m *StatusReport) GetDetails() []byte {
	if m != nil {
		return m.Details
	}
	return nil
}

func init() {
	proto.RegisterType((*StatusReport)(nil), "openiot.StatusReport")
}

func init() { proto.RegisterFile("device.proto", fileDescriptor_870276a56ac00da5) }

var fileDescriptor_870276a56ac00da5 = []byte{
	// 139 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x49, 0x2d, 0xcb,
	0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x2f, 0x48, 0xcd, 0xcb, 0xcc,
	0x2f, 0x51, 0xca, 0xe0, 0xe2, 0x09, 0x2e, 0x49, 0x2c, 0x29, 0x2d, 0x0e, 0x4a, 0x2d, 0xc8, 0x2f,
	0x2a, 0x11, 0x92, 0xe6, 0xe2, 0x84, 0x28, 0x8c, 0xcf, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60,
	0x09, 0xe2, 0x80, 0x08, 0x78, 0xa6, 0x08, 0x29, 0x72, 0xf1, 0xe4, 0xa6, 0x16, 0x17, 0x27, 0xa6,
	0xa7, 0xc6, 0x17, 0x67, 0x56, 0xa5, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0xf0, 0x06, 0x71, 0x43, 0xc5,
	0x82, 0x33, 0xab, 0x52, 0x85, 0x24, 0xb8, 0xd8, 0x53, 0x52, 0x4b, 0x12, 0x33, 0x73, 0x8a, 0x25,
	0x98, 0x15, 0x18, 0x35, 0x78, 0x82, 0x60, 0xdc, 0x24, 0x36, 0xb0, 0xcd, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x8d, 0x06, 0x89, 0x6d, 0x89, 0x00, 0x00, 0x00,
}
