// Code generated by protoc-gen-go. DO NOT EDIT.
// source: join.proto

package home

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JoinRequest struct {
	// Unique Device ID
	DeviceId uint64 `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Device details
	DeviceName         string `protobuf:"bytes,2,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	DeviceManufacturer string `protobuf:"bytes,3,opt,name=device_manufacturer,json=deviceManufacturer,proto3" json:"device_manufacturer,omitempty"`
	DeviceUrl          string `protobuf:"bytes,4,opt,name=device_url,json=deviceUrl,proto3" json:"device_url,omitempty"`
	// protobuf urls
	ProtoStatusMessageUrl string   `protobuf:"bytes,10,opt,name=proto_status_message_url,json=protoStatusMessageUrl,proto3" json:"proto_status_message_url,omitempty"`
	ProtoConfigMessageUrl string   `protobuf:"bytes,11,opt,name=proto_config_message_url,json=protoConfigMessageUrl,proto3" json:"proto_config_message_url,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *JoinRequest) Reset()         { *m = JoinRequest{} }
func (m *JoinRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()    {}
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0580e5afe87d2e40, []int{0}
}

func (m *JoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRequest.Unmarshal(m, b)
}
func (m *JoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRequest.Marshal(b, m, deterministic)
}
func (m *JoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRequest.Merge(m, src)
}
func (m *JoinRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRequest.Size(m)
}
func (m *JoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRequest proto.InternalMessageInfo

func (m *JoinRequest) GetDeviceId() uint64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *JoinRequest) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *JoinRequest) GetDeviceManufacturer() string {
	if m != nil {
		return m.DeviceManufacturer
	}
	return ""
}

func (m *JoinRequest) GetDeviceUrl() string {
	if m != nil {
		return m.DeviceUrl
	}
	return ""
}

func (m *JoinRequest) GetProtoStatusMessageUrl() string {
	if m != nil {
		return m.ProtoStatusMessageUrl
	}
	return ""
}

func (m *JoinRequest) GetProtoConfigMessageUrl() string {
	if m != nil {
		return m.ProtoConfigMessageUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*JoinRequest)(nil), "home.JoinRequest")
}

func init() { proto.RegisterFile("join.proto", fileDescriptor_0580e5afe87d2e40) }

var fileDescriptor_0580e5afe87d2e40 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8e, 0xcd, 0x4a, 0xc4, 0x30,
	0x14, 0x46, 0x69, 0x2d, 0x62, 0x6f, 0x77, 0x11, 0x21, 0x20, 0x62, 0x71, 0xd5, 0x95, 0x2e, 0x5c,
	0xf8, 0x00, 0xae, 0x14, 0xea, 0xa2, 0xe2, 0x3a, 0xc4, 0xf6, 0xb6, 0x46, 0x9a, 0x44, 0xf3, 0x33,
	0x6f, 0x31, 0xef, 0x3c, 0x70, 0x13, 0x98, 0x76, 0xfb, 0x9d, 0x73, 0xe0, 0x03, 0xf8, 0xb5, 0xca,
	0x3c, 0xfe, 0x39, 0x1b, 0x2c, 0xab, 0x7e, 0xac, 0xc6, 0x87, 0x63, 0x09, 0xcd, 0xbb, 0x55, 0x66,
	0xc0, 0xff, 0x88, 0x3e, 0xb0, 0x5b, 0xa8, 0x27, 0x3c, 0xa8, 0x11, 0x85, 0x9a, 0x78, 0xd1, 0x16,
	0x5d, 0x35, 0x5c, 0xa5, 0xe1, 0x6d, 0x62, 0xf7, 0xd0, 0x64, 0x68, 0xa4, 0x46, 0x5e, 0xb6, 0x45,
	0x57, 0x0f, 0x90, 0xa6, 0x0f, 0xa9, 0x91, 0x3d, 0xc1, 0x75, 0x16, 0xb4, 0x34, 0x71, 0x96, 0x63,
	0x88, 0x0e, 0x1d, 0xbf, 0x20, 0x91, 0x25, 0xd4, 0x6f, 0x08, 0xbb, 0x83, 0x9c, 0x8b, 0xe8, 0x56,
	0x5e, 0x91, 0x97, 0x0f, 0x7c, 0xb9, 0x95, 0xbd, 0x00, 0xa7, 0xb3, 0xc2, 0x07, 0x19, 0xa2, 0x17,
	0x1a, 0xbd, 0x97, 0x4b, 0x92, 0x81, 0xe4, 0x1b, 0xe2, 0x9f, 0x84, 0xfb, 0x44, 0x77, 0xe1, 0x68,
	0xcd, 0xac, 0x96, 0x5d, 0xd8, 0x6c, 0xc2, 0x57, 0xc2, 0xe7, 0xf0, 0xfb, 0x92, 0xe6, 0xe7, 0x53,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0x70, 0x78, 0x9f, 0x2a, 0x01, 0x00, 0x00,
}
