// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/sensor/multisensor.proto

package sensor

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MultiSensorStatus struct {
	// An auto incremented value
	Sequence uint32 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Magic number. Always 0x11223344
	Magic uint32 `protobuf:"varint,2,opt,name=magic,proto3" json:"magic,omitempty"`
	// Sensors
	Temperature  *Temperature  `protobuf:"bytes,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humidity     *Humidity     `protobuf:"bytes,4,opt,name=humidity,proto3" json:"humidity,omitempty"`
	AmbientLight *AmbientLight `protobuf:"bytes,5,opt,name=ambient_light,json=ambientLight,proto3" json:"ambient_light,omitempty"`
	// For battery power sensors - current battery state
	Battery              *Battery `protobuf:"bytes,6,opt,name=battery,proto3" json:"battery,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiSensorStatus) Reset()         { *m = MultiSensorStatus{} }
func (m *MultiSensorStatus) String() string { return proto.CompactTextString(m) }
func (*MultiSensorStatus) ProtoMessage()    {}
func (*MultiSensorStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5d97f563f9b4bde, []int{0}
}

func (m *MultiSensorStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiSensorStatus.Unmarshal(m, b)
}
func (m *MultiSensorStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiSensorStatus.Marshal(b, m, deterministic)
}
func (m *MultiSensorStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiSensorStatus.Merge(m, src)
}
func (m *MultiSensorStatus) XXX_Size() int {
	return xxx_messageInfo_MultiSensorStatus.Size(m)
}
func (m *MultiSensorStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiSensorStatus.DiscardUnknown(m)
}

var xxx_messageInfo_MultiSensorStatus proto.InternalMessageInfo

func (m *MultiSensorStatus) GetSequence() uint32 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *MultiSensorStatus) GetMagic() uint32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *MultiSensorStatus) GetTemperature() *Temperature {
	if m != nil {
		return m.Temperature
	}
	return nil
}

func (m *MultiSensorStatus) GetHumidity() *Humidity {
	if m != nil {
		return m.Humidity
	}
	return nil
}

func (m *MultiSensorStatus) GetAmbientLight() *AmbientLight {
	if m != nil {
		return m.AmbientLight
	}
	return nil
}

func (m *MultiSensorStatus) GetBattery() *Battery {
	if m != nil {
		return m.Battery
	}
	return nil
}

type Temperature struct {
	ValueC               float32  `protobuf:"fixed32,1,opt,name=value_c,json=valueC,proto3" json:"value_c,omitempty"`
	ValueF               float32  `protobuf:"fixed32,2,opt,name=value_f,json=valueF,proto3" json:"value_f,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Temperature) Reset()         { *m = Temperature{} }
func (m *Temperature) String() string { return proto.CompactTextString(m) }
func (*Temperature) ProtoMessage()    {}
func (*Temperature) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5d97f563f9b4bde, []int{1}
}

func (m *Temperature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Temperature.Unmarshal(m, b)
}
func (m *Temperature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Temperature.Marshal(b, m, deterministic)
}
func (m *Temperature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Temperature.Merge(m, src)
}
func (m *Temperature) XXX_Size() int {
	return xxx_messageInfo_Temperature.Size(m)
}
func (m *Temperature) XXX_DiscardUnknown() {
	xxx_messageInfo_Temperature.DiscardUnknown(m)
}

var xxx_messageInfo_Temperature proto.InternalMessageInfo

func (m *Temperature) GetValueC() float32 {
	if m != nil {
		return m.ValueC
	}
	return 0
}

func (m *Temperature) GetValueF() float32 {
	if m != nil {
		return m.ValueF
	}
	return 0
}

type Humidity struct {
	Value                float32  `protobuf:"fixed32,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Humidity) Reset()         { *m = Humidity{} }
func (m *Humidity) String() string { return proto.CompactTextString(m) }
func (*Humidity) ProtoMessage()    {}
func (*Humidity) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5d97f563f9b4bde, []int{2}
}

func (m *Humidity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Humidity.Unmarshal(m, b)
}
func (m *Humidity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Humidity.Marshal(b, m, deterministic)
}
func (m *Humidity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Humidity.Merge(m, src)
}
func (m *Humidity) XXX_Size() int {
	return xxx_messageInfo_Humidity.Size(m)
}
func (m *Humidity) XXX_DiscardUnknown() {
	xxx_messageInfo_Humidity.DiscardUnknown(m)
}

var xxx_messageInfo_Humidity proto.InternalMessageInfo

func (m *Humidity) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type AmbientLight struct {
	Value                uint32   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	WhiteValue           uint32   `protobuf:"varint,2,opt,name=white_value,json=whiteValue,proto3" json:"white_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AmbientLight) Reset()         { *m = AmbientLight{} }
func (m *AmbientLight) String() string { return proto.CompactTextString(m) }
func (*AmbientLight) ProtoMessage()    {}
func (*AmbientLight) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5d97f563f9b4bde, []int{3}
}

func (m *AmbientLight) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AmbientLight.Unmarshal(m, b)
}
func (m *AmbientLight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AmbientLight.Marshal(b, m, deterministic)
}
func (m *AmbientLight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AmbientLight.Merge(m, src)
}
func (m *AmbientLight) XXX_Size() int {
	return xxx_messageInfo_AmbientLight.Size(m)
}
func (m *AmbientLight) XXX_DiscardUnknown() {
	xxx_messageInfo_AmbientLight.DiscardUnknown(m)
}

var xxx_messageInfo_AmbientLight proto.InternalMessageInfo

func (m *AmbientLight) GetValue() uint32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *AmbientLight) GetWhiteValue() uint32 {
	if m != nil {
		return m.WhiteValue
	}
	return 0
}

type Battery struct {
	Percent              uint32   `protobuf:"varint,1,opt,name=percent,proto3" json:"percent,omitempty"`
	VoltageMv            uint32   `protobuf:"varint,2,opt,name=voltage_mv,json=voltageMv,proto3" json:"voltage_mv,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Battery) Reset()         { *m = Battery{} }
func (m *Battery) String() string { return proto.CompactTextString(m) }
func (*Battery) ProtoMessage()    {}
func (*Battery) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5d97f563f9b4bde, []int{4}
}

func (m *Battery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Battery.Unmarshal(m, b)
}
func (m *Battery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Battery.Marshal(b, m, deterministic)
}
func (m *Battery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Battery.Merge(m, src)
}
func (m *Battery) XXX_Size() int {
	return xxx_messageInfo_Battery.Size(m)
}
func (m *Battery) XXX_DiscardUnknown() {
	xxx_messageInfo_Battery.DiscardUnknown(m)
}

var xxx_messageInfo_Battery proto.InternalMessageInfo

func (m *Battery) GetPercent() uint32 {
	if m != nil {
		return m.Percent
	}
	return 0
}

func (m *Battery) GetVoltageMv() uint32 {
	if m != nil {
		return m.VoltageMv
	}
	return 0
}

func init() {
	proto.RegisterType((*MultiSensorStatus)(nil), "sensor.MultiSensorStatus")
	proto.RegisterType((*Temperature)(nil), "sensor.Temperature")
	proto.RegisterType((*Humidity)(nil), "sensor.Humidity")
	proto.RegisterType((*AmbientLight)(nil), "sensor.AmbientLight")
	proto.RegisterType((*Battery)(nil), "sensor.Battery")
}

func init() { proto.RegisterFile("proto/sensor/multisensor.proto", fileDescriptor_d5d97f563f9b4bde) }

var fileDescriptor_d5d97f563f9b4bde = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x69, 0xb5, 0x49, 0x9d, 0xb4, 0xa8, 0x6b, 0xc1, 0x45, 0x50, 0x4b, 0x4e, 0x15, 0xa4,
	0x05, 0xc5, 0x83, 0x27, 0xb1, 0xa2, 0x78, 0xb0, 0x97, 0x54, 0xbc, 0x86, 0x6d, 0x1c, 0xdb, 0x85,
	0xfc, 0xa9, 0xc9, 0x24, 0xd2, 0x6f, 0xe1, 0x47, 0x96, 0xec, 0x9f, 0x36, 0xde, 0xf2, 0xde, 0x6f,
	0xde, 0x64, 0x78, 0x2c, 0x5c, 0xac, 0xf3, 0x8c, 0xb2, 0x49, 0x81, 0x69, 0x91, 0xe5, 0x93, 0xa4,
	0x8c, 0x49, 0xea, 0xef, 0xb1, 0x02, 0xcc, 0xd1, 0xca, 0xff, 0x6d, 0xc3, 0xf1, 0xac, 0xa6, 0x73,
	0xa5, 0xe7, 0x24, 0xa8, 0x2c, 0xd8, 0x19, 0x74, 0x0b, 0xfc, 0x2e, 0x31, 0x8d, 0x90, 0xb7, 0x86,
	0xad, 0x51, 0x3f, 0xd8, 0x6a, 0x36, 0x80, 0x4e, 0x22, 0x96, 0x32, 0xe2, 0x6d, 0x05, 0xb4, 0x60,
	0x77, 0xe0, 0x11, 0x26, 0x6b, 0xcc, 0x05, 0x95, 0x39, 0xf2, 0xbd, 0x61, 0x6b, 0xe4, 0xdd, 0x9c,
	0x8c, 0xcd, 0x3f, 0xdf, 0x77, 0x28, 0x68, 0xce, 0xb1, 0x6b, 0xe8, 0xae, 0xca, 0x44, 0x7e, 0x4a,
	0xda, 0xf0, 0x7d, 0x95, 0x39, 0xb2, 0x99, 0x57, 0xe3, 0x07, 0xdb, 0x09, 0x76, 0x0f, 0x7d, 0x91,
	0x2c, 0x24, 0xa6, 0x14, 0xc6, 0x72, 0xb9, 0x22, 0xde, 0x51, 0x91, 0x81, 0x8d, 0x3c, 0x6a, 0xf8,
	0x56, 0xb3, 0xa0, 0x27, 0x1a, 0x8a, 0x5d, 0x81, 0xbb, 0x10, 0x44, 0x98, 0x6f, 0xb8, 0xa3, 0x42,
	0x87, 0x36, 0x34, 0xd5, 0x76, 0x60, 0xb9, 0xff, 0x00, 0x5e, 0xe3, 0x5e, 0x76, 0x0a, 0x6e, 0x25,
	0xe2, 0x12, 0xc3, 0x48, 0x55, 0xd1, 0x0e, 0x1c, 0x25, 0x9f, 0x76, 0xe0, 0x4b, 0x55, 0x61, 0xc1,
	0x8b, 0x3f, 0x84, 0xae, 0x3d, 0xbe, 0x6e, 0x4b, 0xb9, 0x26, 0xab, 0x85, 0xff, 0x0c, 0xbd, 0xe6,
	0xad, 0xff, 0xa7, 0xfa, 0x66, 0x8a, 0x5d, 0x82, 0xf7, 0xb3, 0x92, 0x84, 0xa1, 0x66, 0xba, 0x6f,
	0x50, 0xd6, 0x87, 0x5a, 0x33, 0x05, 0xd7, 0x5c, 0xcf, 0x38, 0xb8, 0x6b, 0xcc, 0x23, 0x4c, 0xc9,
	0xec, 0xb0, 0x92, 0x9d, 0x03, 0x54, 0x59, 0x4c, 0x62, 0x89, 0x61, 0x52, 0x99, 0x25, 0x07, 0xc6,
	0x99, 0x55, 0x0b, 0x47, 0xbd, 0x87, 0xdb, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x99, 0x37, 0x03,
	0x09, 0x31, 0x02, 0x00, 0x00,
}
