// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/sensor/multisensor.proto

package sensors

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MultiSensorStatus struct {
	// An auto incremented value
	Sequence uint32 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Control sum
	Crc uint32 `protobuf:"varint,2,opt,name=crc,proto3" json:"crc,omitempty"`
	// Sensors
	Temperature          *Temperature  `protobuf:"bytes,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humidity             *Humidity     `protobuf:"bytes,4,opt,name=humidity,proto3" json:"humidity,omitempty"`
	AmbientLight         *AmbientLight `protobuf:"bytes,5,opt,name=ambient_light,json=ambientLight,proto3" json:"ambient_light,omitempty"`
	Battery              *Battery      `protobuf:"bytes,6,opt,name=battery,proto3" json:"battery,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MultiSensorStatus) Reset()         { *m = MultiSensorStatus{} }
func (m *MultiSensorStatus) String() string { return proto.CompactTextString(m) }
func (*MultiSensorStatus) ProtoMessage()    {}
func (*MultiSensorStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5d97f563f9b4bde, []int{0}
}

func (m *MultiSensorStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiSensorStatus.Unmarshal(m, b)
}
func (m *MultiSensorStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiSensorStatus.Marshal(b, m, deterministic)
}
func (m *MultiSensorStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiSensorStatus.Merge(m, src)
}
func (m *MultiSensorStatus) XXX_Size() int {
	return xxx_messageInfo_MultiSensorStatus.Size(m)
}
func (m *MultiSensorStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiSensorStatus.DiscardUnknown(m)
}

var xxx_messageInfo_MultiSensorStatus proto.InternalMessageInfo

func (m *MultiSensorStatus) GetSequence() uint32 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *MultiSensorStatus) GetCrc() uint32 {
	if m != nil {
		return m.Crc
	}
	return 0
}

func (m *MultiSensorStatus) GetTemperature() *Temperature {
	if m != nil {
		return m.Temperature
	}
	return nil
}

func (m *MultiSensorStatus) GetHumidity() *Humidity {
	if m != nil {
		return m.Humidity
	}
	return nil
}

func (m *MultiSensorStatus) GetAmbientLight() *AmbientLight {
	if m != nil {
		return m.AmbientLight
	}
	return nil
}

func (m *MultiSensorStatus) GetBattery() *Battery {
	if m != nil {
		return m.Battery
	}
	return nil
}

func init() {
	proto.RegisterType((*MultiSensorStatus)(nil), "sensors.MultiSensorStatus")
}

func init() { proto.RegisterFile("proto/sensor/multisensor.proto", fileDescriptor_d5d97f563f9b4bde) }

var fileDescriptor_d5d97f563f9b4bde = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0x80, 0xe9, 0xa6, 0xdb, 0x78, 0x73, 0xb0, 0x05, 0xc5, 0xb0, 0x83, 0x0c, 0x4f, 0x43, 0xb0,
	0x03, 0x05, 0x0f, 0xde, 0xf4, 0xe4, 0x41, 0x2f, 0x99, 0x77, 0x49, 0xea, 0xc3, 0x05, 0x9a, 0xb6,
	0x26, 0x2f, 0x87, 0xfe, 0x0b, 0x7f, 0xb2, 0x34, 0xa9, 0xb1, 0xbb, 0xbd, 0xf7, 0xbe, 0xef, 0x23,
	0x10, 0xb8, 0x6a, 0x6c, 0x4d, 0xf5, 0xce, 0x61, 0xe5, 0x6a, 0xbb, 0x33, 0xbe, 0x24, 0x1d, 0xe7,
	0x3c, 0x00, 0x36, 0x8d, 0x9b, 0x5b, 0x5f, 0x1e, 0x89, 0x4a, 0x3a, 0x8c, 0xc6, 0xf5, 0xcf, 0x08,
	0x56, 0x6f, 0x5d, 0xb7, 0x0f, 0x68, 0x4f, 0x92, 0xbc, 0x63, 0x6b, 0x98, 0x39, 0xfc, 0xf6, 0x58,
	0x15, 0xc8, 0xb3, 0x4d, 0xb6, 0x5d, 0x88, 0xb4, 0xb3, 0x25, 0x8c, 0x0b, 0x5b, 0xf0, 0x51, 0x38,
	0x77, 0x23, 0x7b, 0x80, 0x39, 0xa1, 0x69, 0xd0, 0x4a, 0xf2, 0x16, 0xf9, 0x78, 0x93, 0x6d, 0xe7,
	0x77, 0xe7, 0x79, 0xff, 0x76, 0xfe, 0xfe, 0xcf, 0xc4, 0x50, 0x64, 0xb7, 0x30, 0x3b, 0x78, 0xa3,
	0x3f, 0x35, 0xb5, 0xfc, 0x24, 0x44, 0xab, 0x14, 0xbd, 0xf4, 0x40, 0x24, 0x85, 0x3d, 0xc2, 0x42,
	0x1a, 0xa5, 0xb1, 0xa2, 0x8f, 0x52, 0x7f, 0x1d, 0x88, 0x9f, 0x86, 0xe6, 0x22, 0x35, 0x4f, 0x91,
	0xbe, 0x76, 0x50, 0x9c, 0xc9, 0xc1, 0xc6, 0x6e, 0x60, 0xaa, 0x24, 0x11, 0xda, 0x96, 0x4f, 0x42,
	0xb5, 0x4c, 0xd5, 0x73, 0xbc, 0x8b, 0x3f, 0x41, 0x4d, 0xc2, 0xcf, 0xdc, 0xff, 0x06, 0x00, 0x00,
	0xff, 0xff, 0xaa, 0xf0, 0x61, 0xae, 0x5d, 0x01, 0x00, 0x00,
}
