/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev */

#ifndef PB_GATEWAY_PROTO_GATEWAY_GENERIC_PB_H_INCLUDED
#define PB_GATEWAY_PROTO_GATEWAY_GENERIC_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _gateway_GatewayStatus {
    uint64_t sequence;
    bool battery_mode;
    uint64_t lora_received;
    uint64_t lora_send;
    uint64_t network_received;
    uint64_t network_send;
    uint64_t lora_crc_error;
    uint64_t spi_timeout;
/* @@protoc_insertion_point(struct:gateway_GatewayStatus) */
} gateway_GatewayStatus;


/* Initializer values for message structs */
#define gateway_GatewayStatus_init_default       {0, 0, 0, 0, 0, 0, 0, 0}
#define gateway_GatewayStatus_init_zero          {0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define gateway_GatewayStatus_sequence_tag       1
#define gateway_GatewayStatus_battery_mode_tag   2
#define gateway_GatewayStatus_lora_received_tag  20
#define gateway_GatewayStatus_lora_send_tag      21
#define gateway_GatewayStatus_network_received_tag 22
#define gateway_GatewayStatus_network_send_tag   23
#define gateway_GatewayStatus_lora_crc_error_tag 40
#define gateway_GatewayStatus_spi_timeout_tag    41

/* Struct field encoding specification for nanopb */
#define gateway_GatewayStatus_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, UINT64, sequence, 1) \
X(a, STATIC, SINGULAR, BOOL, battery_mode, 2) \
X(a, STATIC, SINGULAR, UINT64, lora_received, 20) \
X(a, STATIC, SINGULAR, UINT64, lora_send, 21) \
X(a, STATIC, SINGULAR, UINT64, network_received, 22) \
X(a, STATIC, SINGULAR, UINT64, network_send, 23) \
X(a, STATIC, SINGULAR, UINT64, lora_crc_error, 40) \
X(a, STATIC, SINGULAR, UINT64, spi_timeout, 41)
#define gateway_GatewayStatus_CALLBACK NULL
#define gateway_GatewayStatus_DEFAULT NULL

extern const pb_msgdesc_t gateway_GatewayStatus_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define gateway_GatewayStatus_fields &gateway_GatewayStatus_msg

/* Maximum encoded size of messages (where known) */
#define gateway_GatewayStatus_size               85

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
