/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/gateway/generic.proto */

#ifndef PROTOBUF_C_proto_2fgateway_2fgeneric_2eproto__INCLUDED
#define PROTOBUF_C_proto_2fgateway_2fgeneric_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Gateway__GatewayStatus Gateway__GatewayStatus;


/* --- enums --- */


/* --- messages --- */

struct  _Gateway__GatewayStatus
{
  ProtobufCMessage base;
  /*
   * An auto increment value
   */
  uint64_t sequence;
  /*
   * For devices with backup battery:
   * true if running on battery
   */
  protobuf_c_boolean battery_mode;
  /*
   * Packet counters
   */
  uint64_t lora_received;
  uint64_t lora_send;
  uint64_t network_received;
  uint64_t network_send;
  /*
   * Error counters
   */
  uint64_t lora_crc_error;
  uint64_t spi_timeout;
};
#define GATEWAY__GATEWAY_STATUS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&gateway__gateway_status__descriptor) \
    , 0, 0, 0, 0, 0, 0, 0, 0 }


/* Gateway__GatewayStatus methods */
void   gateway__gateway_status__init
                     (Gateway__GatewayStatus         *message);
size_t gateway__gateway_status__get_packed_size
                     (const Gateway__GatewayStatus   *message);
size_t gateway__gateway_status__pack
                     (const Gateway__GatewayStatus   *message,
                      uint8_t             *out);
size_t gateway__gateway_status__pack_to_buffer
                     (const Gateway__GatewayStatus   *message,
                      ProtobufCBuffer     *buffer);
Gateway__GatewayStatus *
       gateway__gateway_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   gateway__gateway_status__free_unpacked
                     (Gateway__GatewayStatus *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Gateway__GatewayStatus_Closure)
                 (const Gateway__GatewayStatus *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor gateway__gateway_status__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_proto_2fgateway_2fgeneric_2eproto__INCLUDED */
