/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/gateway/generic.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "proto/gateway/generic.pb-c.h"
void   gateway__gateway_status__init
                     (Gateway__GatewayStatus         *message)
{
  static const Gateway__GatewayStatus init_value = GATEWAY__GATEWAY_STATUS__INIT;
  *message = init_value;
}
size_t gateway__gateway_status__get_packed_size
                     (const Gateway__GatewayStatus *message)
{
  assert(message->base.descriptor == &gateway__gateway_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gateway__gateway_status__pack
                     (const Gateway__GatewayStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gateway__gateway_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gateway__gateway_status__pack_to_buffer
                     (const Gateway__GatewayStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gateway__gateway_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gateway__GatewayStatus *
       gateway__gateway_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gateway__GatewayStatus *)
     protobuf_c_message_unpack (&gateway__gateway_status__descriptor,
                                allocator, len, data);
}
void   gateway__gateway_status__free_unpacked
                     (Gateway__GatewayStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gateway__gateway_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor gateway__gateway_status__field_descriptors[8] =
{
  {
    "sequence",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Gateway__GatewayStatus, sequence),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "battery_mode",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Gateway__GatewayStatus, battery_mode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lora_received",
    20,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Gateway__GatewayStatus, lora_received),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lora_send",
    21,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Gateway__GatewayStatus, lora_send),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "network_received",
    22,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Gateway__GatewayStatus, network_received),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "network_send",
    23,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Gateway__GatewayStatus, network_send),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lora_crc_error",
    40,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Gateway__GatewayStatus, lora_crc_error),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "spi_timeout",
    41,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Gateway__GatewayStatus, spi_timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gateway__gateway_status__field_indices_by_name[] = {
  1,   /* field[1] = battery_mode */
  6,   /* field[6] = lora_crc_error */
  2,   /* field[2] = lora_received */
  3,   /* field[3] = lora_send */
  4,   /* field[4] = network_received */
  5,   /* field[5] = network_send */
  0,   /* field[0] = sequence */
  7,   /* field[7] = spi_timeout */
};
static const ProtobufCIntRange gateway__gateway_status__number_ranges[3 + 1] =
{
  { 1, 0 },
  { 20, 2 },
  { 40, 6 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor gateway__gateway_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gateway.GatewayStatus",
  "GatewayStatus",
  "Gateway__GatewayStatus",
  "gateway",
  sizeof(Gateway__GatewayStatus),
  8,
  gateway__gateway_status__field_descriptors,
  gateway__gateway_status__field_indices_by_name,
  3,  gateway__gateway_status__number_ranges,
  (ProtobufCMessageInit) gateway__gateway_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
